### ISSUE TITLE
ctrl shift backspace

### ISSUE THREAD

**Issue by sl5net** [isudox/vscode-jetbrains-keybindings#2]
thanks for your extension:))) !!

i like to have:
ctrl shift backspace (last edit position)

and 

STRG+W

i wort both via autohotkey in windows. if this eventuelly helpful for you. let me know.

**Comment by isudox** [comment]
Thanks for your feedback!
Ctrl + Shift + Backspace is cool, this extension needs to implement it. But.. what does STRG+W do? I don't know.

**Comment by sl5net** [comment]
STRG+W increase selection. word > phrase > line ... etc.

**Comment by isudox** [comment]
Got it, in JetBrains IDEs, the default keybinding for expand selection is ctrl+w (in Windows and Linux), you can use this keybinding :)

**Comment by sl5net** [comment]
for Ctrl + Shift + Backspace 
simply add "Navigate Edits History"
https://stackoverflow.com/questions/50608264/keyboard-shortcut-for-go-back-to-last-edited-position-in-visual-studio-code/50611031#50611031
