### ISSUE TITLE
Keybindings don't match IDEA for mac

### ISSUE THREAD

**Issue by QuantumInformation** [isudox/vscode-jetbrains-keybindings#3]
I suspect they are the windows ones?

**Comment by QuantumInformation** [comment]
Quite a few, I didn't check the others

**Comment by isudox** [comment]
Please list some invalid keybindings, I'll fix it.

**Comment by QuantumInformation** [comment]
alt + up didn't expand the selection, and duplicate line ctrl + d did something else, thats all I remember

I've switched to another plugin

**Comment by isudox** [comment]
on macOS, expand the selection is implemented by option + up, and dup line is implemented by command + d.
Try it.
