### ISSUE TITLE
What's the 'promptV3Features' in the settings?

### ISSUE THREAD

**Issue by vadim-96** [isudox/vscode-jetbrains-keybindings#7]
What does this parameter mean: `jetbrainsKeymap.promptV3Features": true`?

**Comment by dandv** [comment]
My guess is that it displays this popup:

![image](https://user-images.githubusercontent.com/33569/54405847-cfb7fb00-46a5-11e9-8d6f-63e4ac0687b3.png)

However, clicking on Learn more lands on https://marketplace.visualstudio.com/items?itemName=isudox.vscode-jetbrains-keybindings#overview and I can't tell what the new features are.

**Comment by vadim-96** [comment]
@dandv I got it, thanks!
